import {
  type DefinitionEntry,
  type EquationEntry,
  type PedagogyIndex,
  slugify,
} from "@sophie/core/schema";
import { toHtml } from "hast-util-to-html";
import type { Root } from "mdast";
import { toHast } from "mdast-util-to-hast";
import { visit } from "unist-util-visit";

/**
 * Pedagogy index extractor — the load-bearing primitive declared
 * by ADR 0038. PR-C1 implements the `definition` role; other roles
 * (equation, key-insight, figure, misconception) are extracted by
 * PRs C2–C3 using the same pattern.
 *
 * Two layers:
 *
 *   - `extractDefinitions(tree, chapterSlug)` is the **pure
 *     function** that walks one chapter's mdast tree and returns
 *     its `DefinitionEntry[]`. Throws on intra-chapter slug
 *     collisions or missing required titles. Tested with synthetic
 *     ASTs (no MDX parsing in the test loop).
 *
 *   - `indexAccumulator` is the **cross-chapter state**. The
 *     remark plugin (`pedagogyIndexExtractor`, exported below)
 *     calls `clearChapter` then `addDefinitions` for each chapter
 *     it parses. `addDefinitions` throws on cross-chapter slug
 *     collisions (audit invariant #1 — duplicate term across
 *     chapters).
 */

/**
 * Minimal mdxJsxFlowElement shape we read. The unified ecosystem's
 * `mdast-util-mdx-jsx` ships the canonical types, but we only need
 * the attribute-by-name lookup so a narrow shape keeps this module
 * decoupled from the (large) mdx-types surface.
 */
interface MdxJsxFlowElement {
  type: "mdxJsxFlowElement";
  name: string | null;
  attributes: ReadonlyArray<{
    type: string;
    name: string;
    value: string | null | { type: string };
  }>;
  children: ReadonlyArray<unknown>;
}

interface AsideAttributes {
  kind?: string;
  title?: string;
  id?: string;
}

function readAsideAttributes(node: MdxJsxFlowElement): AsideAttributes {
  const out: AsideAttributes = {};
  for (const attr of node.attributes ?? []) {
    if (attr.type !== "mdxJsxAttribute") continue;
    if (typeof attr.value !== "string") continue;
    if (attr.name === "kind") out.kind = attr.value;
    if (attr.name === "title") out.title = attr.value;
    if (attr.name === "id") out.id = attr.value;
  }
  return out;
}

interface KeyEquationAttributes {
  id?: string;
  title?: string;
}

function readKeyEquationAttributes(
  node: MdxJsxFlowElement
): KeyEquationAttributes {
  const out: KeyEquationAttributes = {};
  for (const attr of node.attributes ?? []) {
    if (attr.type !== "mdxJsxAttribute") continue;
    if (typeof attr.value !== "string") continue;
    if (attr.name === "id") out.id = attr.value;
    if (attr.name === "title") out.title = attr.value;
  }
  return out;
}

function renderChildrenToHtml(children: ReadonlyArray<unknown>): string {
  // Wrap in a synthetic root so mdast-util-to-hast can process the
  // body as a top-level subtree. Returns the empty string when no
  // children (definitions are allowed to be header-only).
  if (children.length === 0) return "";
  const synthetic = {
    type: "root" as const,
    children: children as never,
  };
  const hast = toHast(synthetic);
  if (!hast) return "";
  return toHtml(hast);
}

/**
 * Pure extractor. Walks an mdast tree, finds JSX elements named
 * "Aside" with `kind="definition"`, returns one DefinitionEntry
 * per match. Throws when:
 *
 *   - A definition aside is missing a non-empty `title` (the Aside
 *     Zod refinement already catches this at the schema layer; this
 *     is a defense-in-depth check inside the extractor).
 *   - Two definitions in the same chapter slug to the same anchor
 *     (audit invariant #2 — intra-chapter slug collision).
 */
export function extractDefinitions(
  tree: Root,
  chapterSlug: string
): DefinitionEntry[] {
  const out: DefinitionEntry[] = [];
  const seenSlugs = new Set<string>();

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const el = node as MdxJsxFlowElement;
    if (el.name !== "Aside") return;
    const attrs = readAsideAttributes(el);
    if (attrs.kind !== "definition") return;

    const title = attrs.title?.trim();
    if (!title) {
      throw new Error(
        `<Aside kind="definition"> in chapter "${chapterSlug}" is missing a non-empty title.`
      );
    }

    const slug = attrs.id ? slugify(attrs.id) : slugify(title);

    if (seenSlugs.has(slug)) {
      throw new Error(
        `Intra-chapter slug collision in chapter "${chapterSlug}": slug "${slug}" is generated by more than one <Aside kind="definition">. Resolution: add an explicit \`id\` prop to disambiguate.`
      );
    }
    seenSlugs.add(slug);

    out.push({
      term: title,
      slug,
      body: renderChildrenToHtml(el.children),
      chapter: chapterSlug,
      anchor: slug,
    });
  });

  return out;
}

/**
 * Extract the raw TeX source of the FIRST `$$...$$` math block in a
 * KeyEquation's children. Walks the children subtree via
 * `unist-util-visit` and returns the `value` of the first `math` node
 * (display math; the mdast node type produced by `remark-math` for
 * `$$...$$` blocks). Returns `null` when no math node exists —
 * callers treat this as the E6 categorization error.
 *
 * `inlineMath` (the `$x$` AST node type) is deliberately ignored:
 * only display math counts as the canonical-form equation tex.
 */
function extractFirstTex(children: ReadonlyArray<unknown>): string | null {
  let found: string | null = null;
  const synthetic = { type: "root" as const, children: children as never };
  visit(synthetic, "math", (node: { value?: string }) => {
    if (found !== null) return false;
    if (typeof node.value === "string" && node.value.trim().length > 0) {
      found = node.value;
      return false;
    }
    return undefined;
  });
  return found;
}

/**
 * Pure extractor. Walks an mdast tree, finds JSX elements named
 * "KeyEquation", returns one EquationEntry per match with
 * extractor-assigned `number` (per-chapter sequential, starting at
 * 1, in source order). Throws when:
 *
 *   - A KeyEquation is missing a non-empty `id` or `title` (the
 *     KeyEquation Zod props schema already catches this at the
 *     component layer; this is defense in depth inside the
 *     extractor — mirrors `extractDefinitions`'s explicit guard).
 *   - A KeyEquation contains zero `$$` math blocks (E6
 *     categorization error: should be a Callout, not a KeyEquation).
 *   - Two KeyEquations in the same chapter slug to the same anchor
 *     (intra-chapter slug collision; matches definitions' pattern).
 */
export function extractEquations(
  tree: Root,
  chapterSlug: string
): EquationEntry[] {
  const out: EquationEntry[] = [];
  const seenSlugs = new Set<string>();
  let counter = 0;

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const el = node as MdxJsxFlowElement;
    if (el.name !== "KeyEquation") return;
    const attrs = readKeyEquationAttributes(el);

    const id = attrs.id?.trim();
    const title = attrs.title?.trim();
    if (!id) {
      throw new Error(
        `<KeyEquation> in chapter "${chapterSlug}" is missing a non-empty \`id\`.`
      );
    }
    if (!title) {
      throw new Error(
        `<KeyEquation id="${id}"> in chapter "${chapterSlug}" is missing a non-empty \`title\`.`
      );
    }

    const slug = slugify(id);
    if (seenSlugs.has(slug)) {
      throw new Error(
        `Intra-chapter slug collision in chapter "${chapterSlug}": slug "${slug}" is generated by more than one <KeyEquation>. Resolution: change one of the \`id\` props.`
      );
    }
    seenSlugs.add(slug);

    const tex = extractFirstTex(el.children);
    if (tex === null) {
      throw new Error(
        `<KeyEquation id="${id}"> in chapter "${chapterSlug}" contains no \`$$...$$\` math block. Categorization error: KeyEquation must lead with the canonical equation. Resolution: add a \`$$...$$\` block as the first math content, or convert to a <Callout>.`
      );
    }

    counter += 1;
    out.push({
      slug,
      title,
      number: counter,
      tex,
      body: renderChildrenToHtml(el.children),
      chapter: chapterSlug,
      anchor: slug,
    });
  });

  return out;
}

/**
 * Cross-chapter accumulator — state lives on `globalThis` so it
 * survives across Vite environments within a single Astro build.
 *
 * Why globalThis instead of a module-level `Map`: Astro 6 / Vite 7
 * runs separate environments for client and SSR bundles. Each
 * environment has its own module-resolution graph, so a module-
 * level `new Map()` produces TWO independent maps in the same
 * Node process — one written by the MDX-parsing pass, the other
 * read by the page-rendering pass. `globalThis` is genuinely
 * per-process and bridges the environments. Observed during PR-C1
 * with a `pid` + accumulator-size trace.
 *
 * Per ADR 0038's role-aggregation principle. Future entry types
 * (equations, key-insights, figures, misconceptions) attach to
 * this same accumulator under their own collections; PR-C1 only
 * surfaces definitions.
 */
const GLOBAL_KEY = "__sophiePedagogyIndex";

interface GlobalIndexState {
  definitions: Map<string, DefinitionEntry>;
}

function getGlobalState(): GlobalIndexState {
  const g = globalThis as { [GLOBAL_KEY]?: GlobalIndexState };
  if (!g[GLOBAL_KEY]) {
    g[GLOBAL_KEY] = { definitions: new Map() };
  }
  return g[GLOBAL_KEY];
}

class IndexAccumulator {
  /**
   * Drop all entries for a given chapter. Called by the remark
   * plugin before re-extracting a chapter (so re-parses don't
   * accumulate stale entries).
   */
  clearChapter(chapterSlug: string): void {
    const state = getGlobalState();
    for (const [slug, entry] of state.definitions) {
      if (entry.chapter === chapterSlug) {
        state.definitions.delete(slug);
      }
    }
  }

  /**
   * Add a chapter's extracted entries. Throws on cross-chapter
   * slug collision (audit invariant #1).
   */
  addDefinitions(entries: ReadonlyArray<DefinitionEntry>): void {
    const state = getGlobalState();
    // Validate the whole batch BEFORE mutating. Without this two-
    // pass shape, a cross-chapter collision in entry N would leave
    // entries 0..N-1 already in the map — fine while the throw
    // kills the build, but brittle for PR-C2+ which may batch
    // larger role-mixed adds.
    for (const entry of entries) {
      const existing = state.definitions.get(entry.slug);
      if (existing && existing.chapter !== entry.chapter) {
        throw new Error(
          `Definition "${entry.term}" (slug "${entry.slug}") is defined in multiple chapters: "${existing.chapter}" and "${entry.chapter}". Resolution: rename one or consolidate.`
        );
      }
    }
    for (const entry of entries) {
      state.definitions.set(entry.slug, entry);
    }
  }

  /**
   * Snapshot the current accumulator state as a PedagogyIndex.
   * Equations / keyInsights / figures / misconceptions ship empty
   * in PR-C1 (PR-C2 onward populates them).
   */
  asPedagogyIndex(): PedagogyIndex {
    const state = getGlobalState();
    return {
      definitions: Array.from(state.definitions.values()),
      equations: [],
      keyInsights: [],
      figures: [],
      misconceptions: [],
    };
  }
}

export const indexAccumulator = new IndexAccumulator();

/**
 * Default chapter-slug deriver. Matches Astro 6's glob-loader
 * default: the chapter id is the file's BASENAME, without the
 * `.mdx` extension. For
 * `examples/smoke/src/content/chapters/01-foundations/spoiler-alerts.mdx`
 * this yields `"spoiler-alerts"` (matching the URL slug at
 * `/chapters/spoiler-alerts`).
 *
 * Consumer apps with non-default content layouts (e.g. a glob
 * loader configured with `generateId: ...`) pass their own
 * `getChapterSlug` to `pedagogyIndexRemarkPlugin()`.
 */
function defaultGetChapterSlug(filePath: string): string | undefined {
  const match = filePath.match(/[/\\]([^/\\]+)\.mdx$/);
  if (!match) return undefined;
  return match[1];
}

export interface PedagogyIndexRemarkPluginOptions {
  /** Derive a chapter slug from the source file path. Defaults to the
   * standard Astro content-collection layout (see defaultGetChapterSlug). */
  getChapterSlug?: (filePath: string) => string | undefined;
}

interface VFileLike {
  path?: string;
}

/**
 * Remark plugin that wires `extractDefinitions` + `indexAccumulator`
 * into the unified MDX pipeline. Add to `remarkPlugins` in your
 * MDX integration config; runs once per chapter parse.
 *
 * On each chapter parse:
 *   1. Derive the chapter slug from the vfile path.
 *   2. `indexAccumulator.clearChapter(slug)` so re-parses don't
 *      accumulate stale entries.
 *   3. `extractDefinitions(tree, slug)` returns this chapter's
 *      entries.
 *   4. `indexAccumulator.addDefinitions(entries)` aggregates;
 *      throws on cross-chapter slug collision (audit invariant #1).
 *
 * The plugin doesn't mutate the mdast tree — it's extraction-only.
 */
export function pedagogyIndexRemarkPlugin(
  options: PedagogyIndexRemarkPluginOptions = {}
): (tree: Root, file: VFileLike) => void {
  const getChapterSlug = options.getChapterSlug ?? defaultGetChapterSlug;

  return (tree: Root, file: VFileLike) => {
    const filePath = file.path;
    if (!filePath) return;
    const chapterSlug = getChapterSlug(filePath);
    if (!chapterSlug) return;

    indexAccumulator.clearChapter(chapterSlug);
    const entries = extractDefinitions(tree, chapterSlug);
    indexAccumulator.addDefinitions(entries);
  };
}
