import {
  type DefinitionEntry,
  type PedagogyIndex,
  slugify,
} from "@sophie/core/schema";
import { toHtml } from "hast-util-to-html";
import type { Root } from "mdast";
import { toHast } from "mdast-util-to-hast";
import { visit } from "unist-util-visit";

/**
 * Pedagogy index extractor — the load-bearing primitive declared
 * by ADR 0038. PR-C1 implements the `definition` role; other roles
 * (equation, key-insight, figure, misconception) are extracted by
 * PRs C2–C3 using the same pattern.
 *
 * Two layers:
 *
 *   - `extractDefinitions(tree, chapterSlug)` is the **pure
 *     function** that walks one chapter's mdast tree and returns
 *     its `DefinitionEntry[]`. Throws on intra-chapter slug
 *     collisions or missing required titles. Tested with synthetic
 *     ASTs (no MDX parsing in the test loop).
 *
 *   - `indexAccumulator` is the **cross-chapter state**. The
 *     remark plugin (`pedagogyIndexExtractor`, exported below)
 *     calls `clearChapter` then `addDefinitions` for each chapter
 *     it parses. `addDefinitions` throws on cross-chapter slug
 *     collisions (audit invariant #1 — duplicate term across
 *     chapters).
 */

/**
 * Minimal mdxJsxFlowElement shape we read. The unified ecosystem's
 * `mdast-util-mdx-jsx` ships the canonical types, but we only need
 * the attribute-by-name lookup so a narrow shape keeps this module
 * decoupled from the (large) mdx-types surface.
 */
interface MdxJsxFlowElement {
  type: "mdxJsxFlowElement";
  name: string | null;
  attributes: ReadonlyArray<{
    type: string;
    name: string;
    value: string | null | { type: string };
  }>;
  children: ReadonlyArray<unknown>;
}

interface AsideAttributes {
  kind?: string;
  title?: string;
  id?: string;
}

function readAsideAttributes(node: MdxJsxFlowElement): AsideAttributes {
  const out: AsideAttributes = {};
  for (const attr of node.attributes ?? []) {
    if (attr.type !== "mdxJsxAttribute") continue;
    if (typeof attr.value !== "string") continue;
    if (attr.name === "kind") out.kind = attr.value;
    if (attr.name === "title") out.title = attr.value;
    if (attr.name === "id") out.id = attr.value;
  }
  return out;
}

function renderChildrenToHtml(children: ReadonlyArray<unknown>): string {
  // Wrap in a synthetic root so mdast-util-to-hast can process the
  // body as a top-level subtree. Returns the empty string when no
  // children (definitions are allowed to be header-only).
  if (children.length === 0) return "";
  const synthetic = {
    type: "root" as const,
    children: children as never,
  };
  const hast = toHast(synthetic);
  if (!hast) return "";
  return toHtml(hast);
}

/**
 * Pure extractor. Walks an mdast tree, finds JSX elements named
 * "Aside" with `kind="definition"`, returns one DefinitionEntry
 * per match. Throws when:
 *
 *   - A definition aside is missing a non-empty `title` (the Aside
 *     Zod refinement already catches this at the schema layer; this
 *     is a defense-in-depth check inside the extractor).
 *   - Two definitions in the same chapter slug to the same anchor
 *     (audit invariant #2 — intra-chapter slug collision).
 */
export function extractDefinitions(
  tree: Root,
  chapterSlug: string
): DefinitionEntry[] {
  const out: DefinitionEntry[] = [];
  const seenSlugs = new Set<string>();

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const el = node as MdxJsxFlowElement;
    if (el.name !== "Aside") return;
    const attrs = readAsideAttributes(el);
    if (attrs.kind !== "definition") return;

    const title = attrs.title?.trim();
    if (!title) {
      throw new Error(
        `<Aside kind="definition"> in chapter "${chapterSlug}" is missing a non-empty title.`
      );
    }

    const slug = attrs.id ? slugify(attrs.id) : slugify(title);

    if (seenSlugs.has(slug)) {
      throw new Error(
        `Intra-chapter slug collision in chapter "${chapterSlug}": slug "${slug}" is generated by more than one <Aside kind="definition">. Resolution: add an explicit \`id\` prop to disambiguate.`
      );
    }
    seenSlugs.add(slug);

    out.push({
      term: title,
      slug,
      body: renderChildrenToHtml(el.children),
      chapter: chapterSlug,
      anchor: slug,
    });
  });

  return out;
}

/**
 * Cross-chapter accumulator — module-level singleton shared
 * between the remark plugin (which writes) and the Vite virtual
 * module (which reads). Both run in the same Node process during
 * build; the singleton is one instance per process per Node
 * worker.
 *
 * Per ADR 0038's role-aggregation principle, future entry types
 * (equations, key-insights, figures, misconceptions) attach to
 * this same accumulator under their own collections; PR-C1 only
 * surfaces definitions.
 */
class IndexAccumulator {
  private definitions = new Map<string, DefinitionEntry>();

  /**
   * Drop all entries for a given chapter. Called by the remark
   * plugin before re-extracting a chapter (so re-parses don't
   * accumulate stale entries).
   */
  clearChapter(chapterSlug: string): void {
    for (const [slug, entry] of this.definitions) {
      if (entry.chapter === chapterSlug) {
        this.definitions.delete(slug);
      }
    }
  }

  /**
   * Add a chapter's extracted entries. Throws on cross-chapter
   * slug collision (audit invariant #1).
   */
  addDefinitions(entries: ReadonlyArray<DefinitionEntry>): void {
    for (const entry of entries) {
      const existing = this.definitions.get(entry.slug);
      if (existing && existing.chapter !== entry.chapter) {
        throw new Error(
          `Definition "${entry.term}" (slug "${entry.slug}") is defined in multiple chapters: "${existing.chapter}" and "${entry.chapter}". Resolution: rename one or consolidate.`
        );
      }
      this.definitions.set(entry.slug, entry);
    }
  }

  /**
   * Snapshot the current accumulator state as a PedagogyIndex.
   * Equations / keyInsights / figures / misconceptions ship empty
   * in PR-C1 (PR-C2 onward populates them).
   */
  asPedagogyIndex(): PedagogyIndex {
    return {
      definitions: Array.from(this.definitions.values()),
      equations: [],
      keyInsights: [],
      figures: [],
      misconceptions: [],
    };
  }
}

export const indexAccumulator = new IndexAccumulator();
