import type { ReactNode } from "react";
import { z } from "zod";

/**
 * Per-slot extractor-fed payload. Generated by `transformOMIFlow`
 * (MDX build-time pass) from the slot's authored children — title
 * comes from the `title=` attribute, body is pre-rendered HTML from
 * `renderChildrenToHtml`. Mirrors the `RepVerbal.body` / `Objective.body`
 * pattern: HTML strings round-trip through Astro's SSR via
 * `dangerouslySetInnerHTML` without being escaped to literal text.
 */
const OMIFlowSlotPayloadSchema = z.object({
  title: z.string().optional(),
  body: z.string(),
});
export type OMIFlowSlotPayload = z.infer<typeof OMIFlowSlotPayloadSchema>;

/**
 * Props for the root `<OMIFlow>` compound primitive (ADR 0063).
 *
 * Two render modes mirror the `<MultiRep>` precedent (ADR 0043):
 *
 *   - **Author mode** (MDX source + raw-React Storybook/tests): the
 *     three slot components arrive as `children` and the renderer
 *     identifies them by component identity. Used wherever an MDX
 *     build-time transform has NOT pre-processed the JSX.
 *   - **Extractor-fed mode** (post-`transformOMIFlow`): the
 *     `observable` / `model` / `inference` props carry pre-rendered
 *     slot payloads. Authoritative when present; children are
 *     ignored. This is the production MDX path — see
 *     `packages/astro/src/lib/pedagogy-index/transforms/omi-flow.ts`.
 *
 *   - `id` is the stable in-chapter anchor (extractor falls back to
 *     `omi-${slug(concept)}` or `omi-${N}` when absent — see
 *     `extractOMIFlows`).
 *   - `concept` optionally binds the flow to a Notation Registry
 *     concept (ADR 0043) — forward-compat with MultiRep ↔ OMIFlow
 *     cross-link; no v1 audit invariant.
 *
 * Slot-presence and exactly-one invariants are enforced at the
 * EXTRACT phase by `extractOMIFlows` (ADR 0063 strict-3 invariant) —
 * the React renderer trusts well-formed input. v1 schema does not
 * gate it because the renderer is downstream of the extractor.
 */
export const OMIFlowPropsSchema = z.object({
  id: z.string().optional(),
  concept: z.string().optional(),
  children: z.custom<ReactNode>().optional(),
  observable: OMIFlowSlotPayloadSchema.optional(),
  model: OMIFlowSlotPayloadSchema.optional(),
  inference: OMIFlowSlotPayloadSchema.optional(),
});
export type OMIFlowProps = z.infer<typeof OMIFlowPropsSchema>;

/**
 * Props for each `<OMIFlow.{Observable,Model,Inference}>` slot.
 * `title` is optional — when omitted the renderer falls back to the
 * role label ("Observable" / "Model" / "Inference"). When provided,
 * the rendered title becomes `${role-label}: ${title}` (e.g.
 * "Observable: H-α line").
 *
 * The slot's epistemic role is determined by the slot component
 * itself, NOT by an author prop — this is the load-bearing decision
 * #11 from ADR 0063. There is no `role` prop here on purpose.
 */
export const OMIFlowSlotPropsSchema = z.object({
  title: z.string().optional(),
  children: z.custom<ReactNode>(),
});
export type OMIFlowSlotProps = z.infer<typeof OMIFlowSlotPropsSchema>;
