// GENERATED by scripts/build-figures.ts — DO NOT EDIT BY HAND.
// Re-run with `pnpm --filter smoke figures`.
//
// Source: /Users/anna/Teaching/astr201-sp26/assets/figures.yml
// Image files copied into public/figures/ alongside this file.

import type { FigureRegistry } from "@sophie/components/runtime";

export const figures: FigureRegistry = {
  "answering-big-questions": {
    name: "answering-big-questions",
    src: "/figures/answering-the-big-questions-nblm.png",
    alt: "Three-panel diagram: Age of Universe (hourglass icon) - measuring distances to supernovae gives 13.8 billion years; Our Origins (atom icon) - spectroscopy proves iron in our blood was forged in stellar explosions; Are We Alone (planet icon) - we scan exoplanet atmospheres for biosignatures.",
    caption:
      "**What to notice:** The tools we'll learn answer humanity's biggest questions: distance measurements give the universe's age, spectroscopy proves our stellar origins, atmospheric analysis searches for life.",
    credit: "Course illustration (A. Rosen)",
  },
  "cosmic-distance-ladder": {
    name: "cosmic-distance-ladder",
    src: "/figures/cosmic-distance-ladder-nblm.png",
    alt: "Four-rung ladder diagram titled 'The Cosmic Distance Ladder: Building on the Shoulders of Physics'. From bottom to top: Rung 1 Geometry (Parallax), Rung 2 Physics (Cepheids/Standard Candles), Rung 3 Physics (Supernovae/Chandrasekhar Limit), Rung 4 Cosmology (Hubble Flow). Footer text: Our understanding of the vastest scales relies on the microscopic atom.",
    caption:
      "**What to notice:** Each rung calibrates the next. Parallax (geometry) → Cepheids (standard candles) → Supernovae (Chandrasekhar limit) → Hubble Flow (cosmology). We infer the infinite from the infinitesimal.",
    credit: "Course illustration (A. Rosen)",
  },
  "crab-multiwavelength": {
    name: "crab-multiwavelength",
    src: "/figures/crab-multiwavelength-chandra.jpg",
    alt: "Composite image of the Crab Nebula with five individual wavelength views shown below: Radio (red, showing magnetic field structure), Infrared (yellow, warm dust), Optical (green, ionized gas filaments), Ultraviolet (blue), and X-ray (purple, hot plasma and central pulsar jets). The main image combines all wavelengths into a single colorful view.",
    caption:
      "**What to notice:** The same supernova remnant looks completely different at each wavelength. Radio (red) = synchrotron from magnetic fields; Infrared (yellow) = warm dust; Optical (green) = ionized filaments; X-ray (blue/purple) = hot plasma and pulsar jets. Many windows, one truth.",
    credit: "NASA/CXC/SAO",
  },
  "decoder-ring": {
    name: "decoder-ring",
    src: "/figures/decoder-ring-flowchart-nblm.png",
    alt: "Circular flowchart titled 'The Astronomer's Decoder Ring' with Inference (Reality Revealed) at center. Four stages around the circle: Signal (photons arrive from distant objects), Measurement (flux and wavelength quantified through instruments), Model (apply physics like L=4πR²σT⁴), Correction (account for dust and distance). Caption: From photons to physical reality—this is the scientific method in action.",
    caption:
      "**What to notice:** The cycle that makes astronomy a science: Signal → Measurement → Model → Inference → Correction → back to Model. Failed predictions drive model revision.",
    credit: "Course illustration (A. Rosen)",
  },
  "desi-3d-map": {
    name: "desi-3d-map",
    src: "/figures/DESI-Universe-3D-Map.jpg",
    alt: "3D map of galaxy distribution from DESI showing the cosmic web structure. Galaxies form filaments and clusters connected by walls, with large voids between. Color gradient from cyan (nearby) through yellow to red (distant) shows lookback time up to 2.5 billion years. 'You Are Here' marks Earth's position at center.",
    caption:
      "**What to notice:** The cosmic web—galaxies aren't scattered randomly. They cluster into filaments, walls, and voids. You are at the center; colors show distance (cyan = nearby, red = billions of light-years away). Gravity is still pulling these structures together.",
    credit: "DESI Collaboration/NOIRLab/NSF/AURA/Kitt Peak",
  },
  "em-spectrum-temperature": {
    name: "em-spectrum-temperature",
    src: "/figures/em-spectrum-nblm.png",
    alt: "Vertical electromagnetic spectrum showing wavelength bands with corresponding temperatures: Gamma/X-Ray at top for million-degree plasma and black holes, UV/Visible in middle for stars (3,000K–50,000K), Infrared/Radio at bottom for dust (100K) and cold gas (10K). Rainbow colors shown in visible band.",
    caption:
      "**What to notice:** The EM spectrum is a temperature ladder. Gamma/X-ray = million-degree plasma; UV/Visible = stellar surfaces (3,000–50,000 K); Infrared/Radio = dust and cold gas (10–100 K).",
    credit: "Course illustration (A. Rosen)",
  },
  "energy-wavelength-connection": {
    name: "energy-wavelength-connection",
    src: "/figures/energy-wavelength-connection.png",
    alt: "Two-part diagram: Top shows 'The Energy-Wavelength Connection' with equation E = hc/λ and wave illustration transitioning from red (long wavelength) to blue (short wavelength). Bottom shows 'The Temperature Signature' as a color gradient from cool red star (3,000 K) to hot blue star (30,000 K), noting Wien's Law allows temperature calculation from peak color.",
    caption:
      "**What to notice:** E = hc/λ means shorter wavelength = higher energy. Wien's Law lets us calculate temperature from color: cool stars are red (~3,000 K), hot stars are blue (~30,000 K).",
  },
  "forensic-nebula": {
    name: "forensic-nebula",
    src: "/figures/forensic-analysis-of-a-nebula-nblm.png",
    alt: "Annotated nebula image showing three labeled features: (1) Hydrogen-Alpha at 656.3 nm in red regions indicating ionized gas, (2) Doubly-ionized Oxygen [OIII] at 500 nm in blue-green regions indicating extremely low density, (3) Dark Lanes showing silhouettes of interstellar dust blocking the light.",
    caption:
      "**What to notice:** Colors aren't decoration—they're encoded physics. Red = hydrogen (656 nm), blue-green = oxygen (500 nm), dark lanes = dust blocking light.",
    credit: "Course illustration (A. Rosen)",
  },
  "four-observables": {
    name: "four-observables",
    src: "/figures/the-four-observables-nblm.png",
    alt: "Four-panel diagram showing the astronomer's toolkit: Brightness (Flux) - how much energy arrives, Position (Geometry) - where is it on the sky, Wavelength (Spectroscopy) - what colors are present, Timing (Variability) - how does it change.",
    caption:
      "**What to notice:** From billions of kilometers away, we can directly measure only four things. Everything else—mass, radius, temperature, age—is a calculation.",
    credit: "Course illustration (A. Rosen)",
  },
  "lsst-cosmic-treasure-chest": {
    name: "lsst-cosmic-treasure-chest",
    src: "/figures/lsst-cosmic-treasure-chest-zoom.jpg",
    alt: "Deep-field image from Rubin Observatory showing thousands of galaxies of various shapes, sizes, and colors against the dark background of space. Spiral galaxies, elliptical galaxies, and distant faint objects are visible throughout the field.",
    caption:
      "**What to notice:** A single deep-field image contains thousands of galaxies at different distances—each a snapshot from a different cosmic era. This is Rubin Observatory's first light 'Cosmic Treasure Chest'.",
    credit: "Rubin Observatory/NSF/AURA",
  },
  "m51-optical-radio": {
    name: "m51-optical-radio",
    src: "/figures/m51-optical-radio.png",
    alt: "Side-by-side comparison of the Whirlpool Galaxy (M51): Left panel shows optical image with blue-white spiral arms (stars) and dark dust lanes. Right panel shows 21-cm radio emission in red/pink revealing the distribution of cold neutral hydrogen gas extending beyond the visible stellar disk.",
    caption:
      "**What to notice:** Left (optical) shows stars and dust lanes. Right (radio/21-cm) shows cold neutral hydrogen gas. The distributions don't perfectly overlap—different wavelengths reveal different physical components.",
    credit: "NASA/ESA/STScI/AURA (Optical); NRAO/AUI (Radio)",
  },
  "periodic-table-origins": {
    name: "periodic-table-origins",
    src: "/figures/periodic-table-origins-nasa.png",
    alt: "Periodic table color-coded by nucleosynthesis origin: hydrogen and helium from Big Bang (pink), elements like carbon and oxygen from dying low-mass stars (yellow), iron-peak elements from supernovae (orange), heavy elements like gold from merging neutron stars (blue), with some human-made elements (green).",
    caption:
      "**What to notice:** The periodic table is a fossil record of cosmic processes. Different colors = different origins: Big Bang (H, He), dying stars (C, N, O), supernovae (Fe), neutron star mergers (Au, Pt).",
    credit: "NASA/Jennifer Johnson",
  },
  "pillars-hubble-jwst": {
    name: "pillars-hubble-jwst",
    src: "/figures/pillars-hubble-jwst.png",
    alt: "Side-by-side comparison of the Pillars of Creation in the Eagle Nebula: Left panel shows Hubble optical image with dark opaque dust pillars against glowing gas. Right panel shows JWST near-infrared image revealing thousands of previously hidden stars embedded within and behind the pillars.",
    caption:
      "**What to notice:** Left (Hubble optical)—dark, opaque columns block visible light. Right (JWST infrared)—thousands of embedded newborn stars revealed. Infrared penetrates the dust that blocks optical light.",
    credit: "JWST/STScI",
  },
  "prism-spectrum": {
    name: "prism-spectrum",
    src: "/figures/prism-spectrum-nblm.png",
    alt: "Diagram of white light entering a triangular prism and separating into a rainbow spectrum. Labels indicate Cosmic Blue (high energy, short wavelength) at top and Signal Red (low energy, long wavelength) at bottom.",
    caption:
      "**What to notice:** A prism reveals that 'white' light contains many wavelengths. Blue bends more (shorter λ, higher energy); red bends less (longer λ, lower energy).",
    credit: "Course illustration (A. Rosen)",
  },
  "quantum-barcode": {
    name: "quantum-barcode",
    src: "/figures/quantum-barcode-spectroscopy-nlbm.png",
    alt: "Diagram titled 'The Quantum Barcode' showing three parts: Left - an atom with quantized energy levels depicted as a ladder, with electrons occupying specific rungs. Center - 'The Photon Exchange' showing electrons absorbing or emitting photons of exact energy when jumping between levels. Right - 'Three Ways to See the Universe': continuous spectrum (rainbow from hot dense source), absorption spectrum (rainbow with dark lines from cool gas absorbing), and emission spectrum (bright lines on dark background from hot thin gas).",
    caption:
      "**What to notice:** Atoms have quantized energy levels like rungs on a ladder. Electrons jumping between rungs absorb or emit photons of *exact* energies—creating unique spectral fingerprints. Hot dense sources produce continuous spectra; cool gas in front absorbs specific wavelengths; hot thin gas emits specific wavelengths.",
    credit: "Course illustration (A. Rosen)",
  },
  "standard-candles": {
    name: "standard-candles",
    src: "/figures/standard-candles-nblm.png",
    alt: "Two-panel diagram: Left shows Cepheid Variable with sinusoidal light curve where pulse rate reveals wattage. Right shows Type Ia Supernova with white dwarf accreting from companion star, producing consistent peak brightness (~10^9 solar luminosities). Bottom equation: Measure Flux (F) + Know Luminosity (L) → Calculate Distance (d).",
    caption:
      "**What to notice:** Standard candles work because physics predicts their luminosity. Measure flux (F) + know luminosity (L) → calculate distance (d).",
    credit: "Course illustration (A. Rosen)",
  },
  "three-big-questions": {
    name: "three-big-questions",
    src: "/figures/three-big-questions-nblm.png",
    alt: "Three circular images with questions: (1) How does the universe work? - Physics of the cosmos, (2) How did we get here? - Cosmic origins and evolution, (3) Are we alone? - Life in the universe. Footer states: We answer all three using the same superpower: Inference from signals.",
    caption:
      "**What to notice:** Three questions drive modern astronomy—and we answer all of them using the same method: inference from signals.",
    credit: "Course illustration (A. Rosen)",
  },
  "universe-history-nasa": {
    name: "universe-history-nasa",
    src: "/figures/universe-history-nasa.png",
    alt: "NASA timeline diagram titled 'History of the Universe' showing cosmic evolution as an expanding cone from left to right. Major epochs labeled: Inflation (initial expansion), First Particles (neutrons, protons, electrons form), First Nuclei (helium and hydrogen form), First Light (the first atoms form), First Stars (gas and dust condense), Galaxies & Dark Matter (galaxies form in dark matter cradles), Dark Energy (expansion accelerates), Today (humans observe the universe at 13.8 billion years).",
    caption:
      "**What to notice:** The universe has a history. Inflation (10⁻³² s) → First Particles (1 μs) → First Nuclei (3 min) → First Light (380,000 yr) → First Stars (200 Myr) → Galaxies (400 Myr) → Dark Energy (10 Gyr) → Today (13.8 Gyr).",
    credit: "NASA",
  },
  "universe-time-machine": {
    name: "universe-time-machine",
    src: "/figures/universe-time-machine-nblm.png",
    alt: "Timeline showing lookback time: Earth (Now), Moon (1.3 seconds ago), Sun (8 minutes ago), Andromeda galaxy (2.5 million years ago), distant galaxies (10 billion years ago), and cosmic microwave background (Big Bang). Each object shown as thumbnail image above the timeline.",
    caption:
      "**What to notice:** Distance is a time dial. Looking at the Moon = 1.3 seconds ago; the Sun = 8 minutes ago; Andromeda = 2.5 million years ago; distant galaxies = 10 billion years ago.",
    credit: "Course illustration (A. Rosen)",
  },
};
