import { valueToEstree } from "estree-util-value-to-estree";
import type { Root } from "mdast";
import { visit } from "unist-util-visit";
import {
  deriveOMIFlowAnchor,
  parseOMIFlowElement,
} from "../extractors/omi-flow.ts";
import type { MdxJsxFlowElement } from "../jsx-utils.ts";

/**
 * Walks `<OMIFlow>` JSX flow elements and hoists each slot's authored
 * children into explicit `observable` / `model` / `inference` props
 * on the parent. Mirrors `transformMultiRep` (ADR 0043 PR-γ).
 *
 * Why this transform exists: Astro's MDX integration calls inner JSX
 * elements first when rendering. The `<OMIFlow.Observable>` slot
 * marker component returns `null` (it has no body — it's a marker
 * that the parent identifies by `child.type`). So by the time the
 * outer `<OMIFlow>` runs in production SSR, its `children` are
 * three rendered nulls and the slot bodies are gone. This transform
 * intercepts at the AST stage, harvests slot bodies as HTML strings,
 * and replaces the parent's children with three explicit prop
 * payloads that the React renderer dangerously-set-inner-html's.
 *
 * Per ADR 0027: "data crosses the MDX render boundary as props, not
 * as React children." This transform is the build-time half; the
 * React component's extractor-fed mode is the runtime half.
 *
 * Runs AFTER `extractOMIFlows` (read-only pass). Uses the same
 * `parseOMIFlowElement` helper so extractor + transform produce
 * identical slot payloads.
 *
 * The ESTree-wrapped attribute value follows the `transformMultiRep`
 * precedent: lowering passes (`hast-util-to-estree`) read
 * `value.data.estree` and ignore the string `value`. Without the
 * `data.estree` form the runtime prop compiles to
 * `observable={}` (JSXEmptyExpression → undefined) and SSR renders
 * the slot as empty.
 */
export function transformOMIFlow(tree: Root, chapterSlug: string): void {
  let counter = 0;
  const seenAnchors = new Set<string>();

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const parent = node as MdxJsxFlowElement & {
      attributes: Array<{
        type: string;
        name: string;
        value:
          | string
          | boolean
          | null
          | {
              type: string;
              value: string;
              data?: { estree?: unknown };
            };
      }>;
      children: Array<unknown>;
    };
    if (parent.name !== "OMIFlow") return;

    counter += 1;
    const anchor = deriveOMIFlowAnchor(parent, counter);
    if (seenAnchors.has(anchor)) {
      // Mirror the extractor's intra-chapter collision throw so the
      // transform doesn't silently accept input the extractor would
      // reject. The orchestrator runs the extractor first, so in
      // practice this throw fires only if the orchestrator wiring
      // diverges.
      throw new Error(
        `Intra-chapter anchor collision in chapter "${chapterSlug}": OMIFlow anchor "${anchor}" generated by more than one source. (ADR 0063 anchor invariant.)`
      );
    }
    seenAnchors.add(anchor);

    const parsed = parseOMIFlowElement(parent, chapterSlug, anchor);

    // Replace authored children with explicit slot-payload props.
    // Each prop is an ESTree-encoded object literal so MDX lowers
    // it to a real expression rather than a JSXEmptyExpression.
    parent.children = [];

    for (const [propName, payload] of [
      ["observable", parsed.observable],
      ["model", parsed.model],
      ["inference", parsed.inference],
    ] as const) {
      const expr = valueToEstree(payload);
      parent.attributes.push({
        type: "mdxJsxAttribute",
        name: propName,
        value: {
          type: "mdxJsxAttributeValueExpression",
          value: JSON.stringify(payload),
          data: {
            estree: {
              type: "Program",
              sourceType: "module",
              body: [
                {
                  type: "ExpressionStatement",
                  expression: expr,
                },
              ],
            },
          },
        },
      });
    }
  });
}
