import { z } from "zod";
import { NonEmptyString } from "./primitives.js";

/**
 * Intervention schemas per ADR 0044 + 2026-05-17 design hardening.
 *
 * Three artifacts in this file (framework-pure data shapes):
 * - InterventionEntrySchema: the pedagogy-index entry (one per
 *   `<Intervention>` block in a chapter), consumed by the audit
 *   invariants MG3/MG4/I1/I2/I3 (PR-δ) and by the AI ledger
 *   (ADR 0042).
 * - InterventionLibraryEntrySchema: one entry per canonical
 *   intervention in `intervention-index.ts` (12 entries at v1 across
 *   4 families). Forward-compat slots for DOI/bibtex/template are
 *   reserved (design §F4/F5); the `move:` field binds to ADR 0041's
 *   future move-index.ts (I4 audit at v2).
 * - InterventionFamilySchema + InterventionDepthSchema:
 *   shared enumerations.
 *
 * The React-aware `InterventionPropsSchema` (component callsite
 * shape, which references `ReactNode`) lives next to the component
 * in `@sophie/components` (mirrors KeyEquation precedent) since
 * `@sophie/core` is framework-pure per ADR 0001.
 *
 * `type` is `z.string()` (not a strict union) so adding a new
 * canonical intervention is a one-file change to `intervention-index.ts`,
 * no schema bump. The I2 audit invariant (PR-δ) validates that every
 * `<Intervention type="X">` either matches an `intervention-index.ts`
 * entry or declares `type="custom"` with a non-empty `name`. The
 * runtime component looks the entry up at render time for the
 * citation chip; `type="custom"` skips the lookup.
 *
 * `addresses` accepts `string | string[]` at the component layer
 * (design §F2) so v2 multi-target use is non-breaking. The PR-γ
 * extractor normalizes to an array; the index entry stores the
 * normalized form so the audit (I1) walks a single shape.
 */

export const InterventionFamilySchema = z.enum([
  "confrontation",
  "bridging",
  "restructuring",
  "reinforcement",
]);

export type InterventionFamily = z.infer<typeof InterventionFamilySchema>;

export const InterventionDepthSchema = z.enum(["light", "substantial"]);

export type InterventionDepth = z.infer<typeof InterventionDepthSchema>;

export const InterventionEntrySchema = z.object({
  /**
   * Canonical-intervention slug OR the literal "custom". Matches the
   * source `<Intervention type="…">` value verbatim; no normalization
   * applied at extract time.
   */
  type: NonEmptyString,
  /** Only present (and required) when `type === "custom"`. */
  name: NonEmptyString.optional(),
  /**
   * Resolved misconception slug(s). The PR-γ extractor rewrites
   * `addresses="this"` to the enclosing `<Aside kind="misconception"
   * name="X">`'s name. Always normalized to an array at this layer
   * (the audit consumes the array form).
   */
  addresses: z.array(NonEmptyString).min(1),
  /** Serialized intervention prose (HTML-rendered children body). */
  body: NonEmptyString,
  /** Explicit limits if author supplied (Clement 1993 pattern). */
  limits: NonEmptyString.optional(),
  /** Depth coverage metadata (MG4 audit consumes this). */
  depth: InterventionDepthSchema,
  /** Chapter slug. */
  chapter: NonEmptyString,
  /**
   * Anchor id, auto-generated by the PR-γ extractor as
   * `intervention-${type-or-name-slug}-${index-in-chapter}`. Stable
   * across re-renders so cross-references survive content edits.
   */
  anchor: NonEmptyString,
});

export type InterventionEntry = z.infer<typeof InterventionEntrySchema>;

export const InterventionLibraryEntrySchema = z.object({
  /** Canonical slug (e.g., "contrasting-cases"). Matches `<Intervention type="…">`. */
  name: NonEmptyString,
  /** One of 4 cognitive-science families per ADR 0044. */
  family: InterventionFamilySchema,
  /** One-sentence summary surfaced in MyST reference docs + AI authoring tooltips. */
  description: NonEmptyString,
  /**
   * Plain-string citation at v1 (e.g., "Bransford & Schwartz 1999").
   * Structured DOI/bibtex slots are reserved for v2; see
   * `citation_doi` and `citation_bibtex` below.
   */
  citation: NonEmptyString,
  /**
   * Which misconception-graph families this intervention typically
   * targets. Free-form slugs at v1 (no platform catalog of misconception
   * families); used as an authoring hint, not enforced by audit.
   */
  addresses_families: z.array(NonEmptyString),
  /**
   * Binding to ADR 0041's teaching-move library. Free-form slug at v1;
   * the I4 audit invariant (verifying the move resolves to a real entry
   * in `move-index.ts`) is deferred until move-index.ts ships — declared
   * here as the forward-compat seam.
   */
  move: NonEmptyString,
  /** v2-reserved: structured DOI citation. */
  citation_doi: NonEmptyString.optional(),
  /** v2-reserved: full BibTeX entry. */
  citation_bibtex: NonEmptyString.optional(),
  /** v2-reserved: scaffolding template body for AI authoring per ADR 0030. */
  template_body: NonEmptyString.optional(),
});

export type InterventionLibraryEntry = z.infer<
  typeof InterventionLibraryEntrySchema
>;
