import { z } from "zod";
import { NonEmptyString } from "./primitives.js";

/**
 * Intervention schemas per ADR 0044 + 2026-05-17 design hardening.
 *
 * Three artifacts in this file (framework-pure data shapes):
 * - InterventionEntrySchema: the pedagogy-index entry (one per
 *   `<Intervention>` block in a chapter), consumed by the audit
 *   invariants MG3/MG4/I1/I2/I3 (PR-δ) and by the AI ledger
 *   (ADR 0042).
 * - InterventionLibraryEntrySchema: one entry per canonical
 *   intervention in `intervention-index.ts` (12 entries at v1 across
 *   4 families). Forward-compat slots for DOI/bibtex/template are
 *   reserved (design §F4/F5); the `move:` field binds to ADR 0041's
 *   future move-index.ts (I4 audit at v2).
 * - InterventionFamilySchema + InterventionDepthSchema:
 *   shared enumerations.
 *
 * The React-aware `InterventionPropsSchema` (component callsite
 * shape, which references `ReactNode`) lives next to the component
 * in `@sophie/components` (mirrors KeyEquation precedent) since
 * `@sophie/core` is framework-pure per ADR 0001.
 *
 * `type` is `z.string()` (not a strict union) so adding a new
 * canonical intervention is a one-file change to `intervention-index.ts`,
 * no schema bump. The I2 audit invariant (PR-δ) validates that every
 * `<Intervention type="X">` either matches an `intervention-index.ts`
 * entry or declares `type="custom"` with a non-empty `name`. The
 * runtime component looks the entry up at render time for the
 * citation chip; `type="custom"` skips the lookup.
 *
 * `addresses` accepts `string | string[]` at the component layer
 * (design §F2) so v2 multi-target use is non-breaking. The PR-γ
 * extractor normalizes to an array; the index entry stores the
 * normalized form so the audit (I1) walks a single shape.
 *
 * Both object schemas are `.strict()` — unknown keys fail parse rather
 * than being silently stripped. The v2-reserved forward-compat slots on
 * `InterventionLibraryEntrySchema` (`citation_doi`, `citation_bibtex`,
 * `template_body` per design §F4/F5) are explicitly declared so they pass
 * parse; .strict() makes a typo like `citation_DOI` (case drift) or
 * `templateBody` (camelCase instead of snake_case) fail rather than
 * silently drop. The `superRefine` constraint on `InterventionEntrySchema`
 * (custom type ⇒ name required) chains *after* .strict(); both run.
 * Mirrors the same discipline applied across `equation-biography.ts`
 * (Phase B audit §2.1) so all three pedagogical-core families share one
 * schema posture.
 */

export const InterventionFamilySchema = z.enum([
  "confrontation",
  "bridging",
  "restructuring",
  "reinforcement",
]);

export type InterventionFamily = z.infer<typeof InterventionFamilySchema>;

export const InterventionDepthSchema = z.enum(["light", "substantial"]);

export type InterventionDepth = z.infer<typeof InterventionDepthSchema>;

export const InterventionEntrySchema = z
  .object({
    /**
     * Canonical-intervention slug OR the literal "custom". Matches the
     * source `<Intervention type="…">` value verbatim; no normalization
     * applied at extract time.
     */
    type: NonEmptyString,
    /**
     * Only present (and required) when `type === "custom"`. The
     * `.superRefine` below enforces this — extracting a custom
     * intervention without a `name` produces an audit-correctness
     * gap (the I2 invariant relies on `name` for the catalog
     * fallback at audit time).
     */
    name: NonEmptyString.optional(),
    /**
     * Resolved misconception slug(s). The PR-γ extractor rewrites
     * `addresses="this"` to the enclosing `<Aside kind="misconception"
     * name="X">`'s name. Always normalized to an array at this layer
     * (the audit consumes the array form).
     */
    addresses: z.array(NonEmptyString).min(1),
    /** Serialized intervention prose (HTML-rendered children body). */
    body: NonEmptyString,
    /** Explicit limits if author supplied (Clement 1993 pattern). */
    limits: NonEmptyString.optional(),
    /** Depth coverage metadata (MG4 audit consumes this). */
    depth: InterventionDepthSchema,
    /** Chapter slug. */
    chapter: NonEmptyString,
    /**
     * Anchor id, auto-generated by the PR-γ extractor as
     * `intervention-${type-or-name-slug}-${index-in-chapter}`. Stable
     * across re-renders so cross-references survive content edits.
     */
    anchor: NonEmptyString,
  })
  .strict()
  .superRefine((data, ctx) => {
    // Mirror the InterventionPropsSchema rule: type="custom" requires
    // `name`. The extractor pulls this constraint forward from the
    // component callsite; emitting a `type="custom"` entry without
    // `name` would leave the audit's I2 invariant unable to render a
    // human-readable label for the custom move.
    if (data.type === "custom" && data.name === undefined) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["name"],
        message:
          '`name` is required when `type="custom"` — the extractor must propagate the source `<Intervention name="…">` prop.',
      });
    }
  });

export type InterventionEntry = z.infer<typeof InterventionEntrySchema>;

export const InterventionLibraryEntrySchema = z
  .object({
    /** Canonical slug (e.g., "contrasting-cases"). Matches `<Intervention type="…">`. */
    name: NonEmptyString,
    /** One of 4 cognitive-science families per ADR 0044. */
    family: InterventionFamilySchema,
    /** One-sentence summary surfaced in MyST reference docs + AI authoring tooltips. */
    description: NonEmptyString,
    /**
     * Plain-string citation at v1 (e.g., "Bransford & Schwartz 1999").
     * Structured DOI/bibtex slots are reserved for v2; see
     * `citation_doi` and `citation_bibtex` below.
     */
    citation: NonEmptyString,
    /**
     * Which misconception-graph families this intervention typically
     * targets. Free-form slugs at v1 (no platform catalog of misconception
     * families); used as an authoring hint, not enforced by audit.
     */
    addresses_families: z.array(NonEmptyString),
    /**
     * Binding to ADR 0041's teaching-move library. Free-form slug at v1;
     * the I4 audit invariant (verifying the move resolves to a real entry
     * in `move-index.ts`) is deferred until move-index.ts ships — declared
     * here as the forward-compat seam.
     */
    move: NonEmptyString,
    /** v2-reserved: structured DOI citation. */
    citation_doi: NonEmptyString.optional(),
    /** v2-reserved: full BibTeX entry. */
    citation_bibtex: NonEmptyString.optional(),
    /** v2-reserved: scaffolding template body for AI authoring per ADR 0030. */
    template_body: NonEmptyString.optional(),
  })
  .strict();

export type InterventionLibraryEntry = z.infer<
  typeof InterventionLibraryEntrySchema
>;
