import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import postcss from "postcss";
import postcssModules from "postcss-modules";

// Builds CSS Module wrappers for @sophie/figures-astro. Mirrors the
// @sophie/components and @sophie/figures-kit scripts. See those for
// the rationale (per-package self-contained for now; shared monorepo
// tooling extraction deferred per DRY-when-paid + ADR 0023).

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const srcDir = join(pkgRoot, "src");
const distDir = join(pkgRoot, "dist");

interface ProcessResult {
  distCssPath: string;
  relFromSrc: string;
  classCount: number;
}

async function findCssModules(dir: string): Promise<string[]> {
  const out: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await findCssModules(full)));
    } else if (entry.isFile() && entry.name.endsWith(".module.css")) {
      out.push(full);
    }
  }
  return out;
}

async function processOne(srcPath: string): Promise<ProcessResult> {
  const css = await readFile(srcPath, "utf8");
  const relFromSrc = relative(srcDir, srcPath);
  const distCssPath = join(distDir, relFromSrc);
  const distJsPath = join(distDir, `${basename(srcPath)}.js`);

  let exportTokens: Record<string, string> = {};
  const result = await postcss([
    postcssModules({
      generateScopedName: "[local]_[hash:base64:5]",
      getJSON: (_filename, json) => {
        exportTokens = json;
      },
    }),
  ]).process(css, { from: srcPath, to: distCssPath });

  await mkdir(dirname(distCssPath), { recursive: true });
  await writeFile(distCssPath, result.css, "utf8");

  const companion = [
    `const styles = ${JSON.stringify(exportTokens, null, 2)};`,
    `export default styles;`,
    "",
  ].join("\n");
  await writeFile(distJsPath, companion, "utf8");

  return {
    distCssPath,
    relFromSrc,
    classCount: Object.keys(exportTokens).length,
  };
}

const files = await findCssModules(srcDir);
if (files.length === 0) {
  console.log("No .module.css files found under src/.");
  process.exit(0);
}

console.log(`Processing ${files.length} CSS Module file(s):`);
const results = await Promise.all(files.map(processOne));
for (const r of results) {
  console.log(
    `  ${r.relFromSrc} → ${relative(pkgRoot, r.distCssPath)} + dist/${basename(r.distCssPath)}.js (${r.classCount} classes)`
  );
}

results.sort((a, b) => a.relFromSrc.localeCompare(b.relFromSrc));
const bundleParts: string[] = [
  "/* @sophie/figures-astro — bundled component stylesheets.",
  " * Generated by scripts/build-css-modules.ts. Do not edit by hand.",
  " * Side-effect-imported alongside @sophie/components/styles.css and",
  " * @sophie/figures-kit/styles.css.",
  " */",
  "",
];
for (const r of results) {
  const mangled = await readFile(r.distCssPath, "utf8");
  bundleParts.push(`/* ${r.relFromSrc} */`);
  bundleParts.push(mangled.trimEnd());
  bundleParts.push("");
}
const bundlePath = join(distDir, "styles.css");
await mkdir(distDir, { recursive: true });
await writeFile(bundlePath, bundleParts.join("\n"), "utf8");
console.log(
  `\nWrote ${relative(pkgRoot, bundlePath)} (${results.length} files concatenated)`
);
console.log("CSS Modules build complete.");
