import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { anchors, brand, darkBrand } from "../src/anchors.ts";
import { checkContrast } from "./contrast.ts";
import { generateCSS } from "./generate-css.ts";
import { generateTailwind } from "./generate-tailwind.ts";

const here = dirname(fileURLToPath(import.meta.url));
const distDir = join(here, "..", "dist");

// Brand text contrast — checked against the page bg (`paper` in light,
// `darkBg` in dark) rather than the title-bar tint. The title bar is
// `color-mix(brand X%, surface-1)`, which differs from pure paper/darkBg
// by only a few luminance points — the page-bg check is the closest
// approximation we can make with hex-only inputs (the contrast utility
// can't parse color-mix(in oklch, …)). Verified visually in component
// VR baselines per ADR 0057.
const checks = [
  checkContrast("brand.teal.text on paper", brand.teal.text, anchors.paper),
  checkContrast("brand.rose.text on paper", brand.rose.text, anchors.paper),
  checkContrast("brand.violet.text on paper", brand.violet.text, anchors.paper),
  checkContrast(
    "darkBrand.teal.text on darkBg",
    darkBrand.teal.text,
    anchors.darkBg
  ),
  checkContrast(
    "darkBrand.rose.text on darkBg",
    darkBrand.rose.text,
    anchors.darkBg
  ),
  checkContrast(
    "darkBrand.violet.text on darkBg",
    darkBrand.violet.text,
    anchors.darkBg
  ),
];

const failures = checks.filter((c) => !c.passesAA);
if (failures.length > 0) {
  console.error("WCAG AA contrast check failed for:");
  for (const f of failures) {
    console.error(
      `  ${f.label}: ${f.fg} on ${f.bg} = ${f.ratio.toFixed(2)}:1 (need ≥ 4.5:1)`
    );
  }
  console.error(
    "Tune the failing brand-*-text hex in packages/theme/src/anchors.ts."
  );
  process.exit(1);
}

console.log("WCAG AA contrast check:");
for (const c of checks) {
  console.log(`  ${c.label}: ${c.ratio.toFixed(2)}:1  ✓`);
}

// Self-hosted IBM Plex font imports. Bundlers (Vite/Astro/Storybook)
// resolve these `@import` statements at consumer build time, inline the
// upstream @fontsource @font-face declarations, and emit fingerprinted
// .woff2 assets. Keeps font wiring at the design-token layer where the
// `--sophie-font-*` variables also live, so consumers reach for the
// single source of truth via `@sophie/theme/fonts`.
const fontsCSS = `/* Generated by @sophie/theme. Do not edit by hand. */

/* IBM Plex Sans (variable axis 100–700) — body, display, UI chrome. */
@import "@fontsource-variable/ibm-plex-sans";

/* Fraunces (variable axis SOFT 0–100 + opsz + WGHT 100–900) — display
 * serif for h1 / h2 chapter and Part headings. Distinctive but
 * restrained; pairs with IBM Plex Sans body. Reserved for headings
 * (and rare body emphasis) — body prose stays sans. */
@import "@fontsource-variable/fraunces";

/* IBM Plex Mono — code blocks + <CodeCell> + inline code.
 * Static-weight package: load 400 (regular) and 600 (semibold) only.
 * Italic + other weights ship later if needed. */
@import "@fontsource/ibm-plex-mono/400.css";
@import "@fontsource/ibm-plex-mono/600.css";
`;

// KaTeX inline-math sizing override. KaTeX defaults `.katex` to ~1.21em
// (calibrated for display-math prominence); against 17px prose that
// makes inline equations dominate the line and feel imported rather
// than native. Shrinking inline `.katex` to 1.05em lets math sit *with*
// the surrounding text. Display math is reset back to the KaTeX default
// because `.katex-display` already centers + scales for prominence, and
// KaTeX's subscript/superscript metrics are tuned to the larger size.
const mathCSS = `/* Generated by @sophie/theme. Do not edit by hand. */

/* Inline math: 1.05× surrounding text (down from KaTeX's default ~1.21×).
 * Lets <em>L = 4πR²σT⁴</em> sit *with* prose rather than dominating. */
.katex {
  font-size: 1.05em;
}

/* Display math: restore KaTeX's default so the centered block reads as
 * "this is a named equation worth pausing on" and KaTeX's sub/sup
 * positioning stays correct (those metrics are tuned to 1.21em). */
.katex-display > .katex {
  font-size: 1.21em;
}
`;

// Base/element layer (ADR 0095). The missing layer between tokens
// (theme.css) and component rules (@sophie/components styles.css): it
// styles bare HTML elements from design tokens so EVERY route — chapter
// shell and course spine alike — has sane element defaults, not just
// routes that mount the chapter shell (where typography previously lived
// only on `.sophie-*` classes in textbook-layout.css). Loaded once via
// <SophieHead>. Deliberately carries NO `box-sizing` reset (would churn
// component VR baselines) and is not loaded into Storybook, so component
// isolation is unaffected. Cascade: tokens → base → components.
const baseCSS = `/* Generated by @sophie/theme. Do not edit by hand.
 * Base/element layer (ADR 0095) — token-driven defaults for bare HTML
 * elements, applied on every route via <SophieHead>. Sits between tokens
 * (@sophie/theme/css) and component rules (@sophie/components/styles.css).
 */

html {
  color-scheme: light dark;
  -webkit-text-size-adjust: 100%;
  text-size-adjust: 100%;
}

body {
  margin: 0;
  font-family: var(--sophie-font-sans);
  font-size: var(--sophie-text-body);
  line-height: var(--sophie-leading-prose);
  color: var(--sophie-text);
  background: var(--sophie-bg);
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

/* Headings default to the display serif at semibold; component module
 * CSS (and .sophie-content) overrides per-context via higher specificity.
 * Bare element rule keeps unwrapped prose (e.g. info-page MDX) on-system
 * rather than Times. */
h1, h2, h3, h4, h5, h6 {
  font-family: var(--sophie-font-serif);
  font-weight: 600;
  line-height: var(--sophie-leading-tight);
}

a {
  color: var(--sophie-link);
  text-underline-offset: 0.15em;
}
a:hover {
  color: var(--sophie-link-hover);
}

code, kbd, samp, pre {
  font-family: var(--sophie-font-mono);
}

:focus-visible {
  outline: var(--sophie-focus-width) solid var(--sophie-focus-color);
  outline-offset: 2px;
}
`;

await mkdir(distDir, { recursive: true });
await writeFile(join(distDir, "theme.css"), generateCSS(), "utf8");
await writeFile(join(distDir, "fonts.css"), fontsCSS, "utf8");
await writeFile(join(distDir, "math.css"), mathCSS, "utf8");
await writeFile(join(distDir, "base.css"), baseCSS, "utf8");
await writeFile(join(distDir, "tailwind.css"), generateTailwind(), "utf8");

console.log(`Wrote ${join(distDir, "theme.css")}`);
console.log(`Wrote ${join(distDir, "fonts.css")}`);
console.log(`Wrote ${join(distDir, "math.css")}`);
console.log(`Wrote ${join(distDir, "base.css")}`);
console.log(`Wrote ${join(distDir, "tailwind.css")}`);
