import {
  anchors,
  brand,
  focus,
  fontStacks,
  layout,
  leadings,
  radii,
  sizes,
  spacings,
  status,
  weights,
} from "../src/anchors.ts";

interface ColorMode {
  bg: string;
  fg: string;
}

const light: ColorMode = { bg: anchors.paper, fg: anchors.ink };
const dark: ColorMode = { bg: anchors.ink, fg: anchors.paper };

function colorBlock(mode: ColorMode): string {
  const { bg, fg } = mode;
  return [
    `--sophie-bg: ${bg};`,
    `--sophie-surface-1: color-mix(in oklch, ${bg} 92%, ${fg});`,
    `--sophie-surface-2: color-mix(in oklch, ${bg} 86%, ${fg});`,
    `--sophie-surface-3: color-mix(in oklch, ${bg} 80%, ${fg});`,
    `--sophie-text: color-mix(in oklch, ${fg} 88%, ${bg});`,
    `--sophie-text-2: color-mix(in oklch, ${fg} 64%, ${bg});`,
    `--sophie-text-muted: color-mix(in oklch, ${fg} 46%, ${bg});`,
    `--sophie-text-faint: color-mix(in oklch, ${fg} 32%, ${bg});`,
    `--sophie-border: color-mix(in oklch, ${fg} 8%, transparent);`,
    `--sophie-border-subtle: color-mix(in oklch, ${fg} 5%, transparent);`,
    `--sophie-link: color-mix(in oklch, var(--sophie-accent) 70%, var(--sophie-text));`,
    // Scheme-aware card shadow. Derived from ${fg} (=ink in light mode,
    // paper in dark mode) so the shadow color adapts to scheme instead
    // of being invisible in dark mode like a hardcoded #0f1115 would be.
    // 4% concentration matches the original visual in light mode.
    `--sophie-shadow-card: 0 1px 3px color-mix(in oklch, ${fg} 4%, transparent);`,
  ].join("\n    ");
}

function modeInvariantBlock(): string {
  return [
    `--sophie-brand-teal: ${brand.teal.fill};`,
    `--sophie-brand-teal-text: ${brand.teal.text};`,
    `--sophie-brand-rose: ${brand.rose.fill};`,
    `--sophie-brand-rose-text: ${brand.rose.text};`,
    `--sophie-brand-violet: ${brand.violet.fill};`,
    `--sophie-brand-violet-text: ${brand.violet.text};`,
    `--sophie-status-success: ${status.success};`,
    `--sophie-status-warning: ${status.warning};`,
    `--sophie-status-danger: ${status.danger};`,
    "--sophie-accent: var(--sophie-brand-teal);",
    "--sophie-link-hover: var(--sophie-accent);",
  ].join("\n  ");
}

function typographyBlock(): string {
  return [
    `--sophie-font-sans: ${fontStacks.sans};`,
    `--sophie-font-serif: ${fontStacks.serif};`,
    `--sophie-font-mono: ${fontStacks.mono};`,
    ...Object.entries(sizes).map(([k, v]) => `--sophie-text-${k}: ${v};`),
    `--sophie-leading-tight: ${leadings.tight};`,
    `--sophie-leading-prose: ${leadings.prose};`,
    ...Object.entries(weights).map(([k, v]) => `--sophie-weight-${k}: ${v};`),
  ].join("\n  ");
}

function spacingBlock(): string {
  return Object.entries(spacings)
    .map(([k, v]) => `--sophie-space-${k}: ${v};`)
    .join("\n  ");
}

function radiiBlock(): string {
  return Object.entries(radii)
    .map(([k, v]) => `--sophie-radius-${k}: ${v};`)
    .join("\n  ");
}

function layoutBlock(): string {
  return [
    `--sophie-prose-max-width: ${layout.proseMaxWidth};`,
    `--sophie-content-padding-inline: ${layout.contentPaddingInline};`,
  ].join("\n  ");
}

function focusBlock(): string {
  return [
    `--sophie-focus-width: ${focus.width};`,
    "--sophie-focus-color: color-mix(in oklch, var(--sophie-accent) 55%, transparent);",
  ].join("\n  ");
}

export function generateCSS(): string {
  return `/* Generated by @sophie/theme. Do not edit by hand. */

:root {
  color-scheme: light dark;

  /* Color — light */
  ${colorBlock(light)}

  /* Brand + status (mode-invariant) */
  ${modeInvariantBlock()}

  /* Typography */
  ${typographyBlock()}

  /* Spacing */
  ${spacingBlock()}

  /* Radii */
  ${radiiBlock()}

  /* Layout */
  ${layoutBlock()}

  /* Focus ring */
  ${focusBlock()}
}

[data-theme="dark"] {
  /* Color — dark (explicit override) */
    ${colorBlock(dark)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
    /* Color — dark (system preference) */
    ${colorBlock(dark)}
  }
}
`;
}
