const colors = [
  "bg",
  "surface-1",
  "surface-2",
  "surface-3",
  "text",
  "text-2",
  "text-muted",
  "text-faint",
  "border",
  "border-subtle",
  "brand-teal",
  "brand-teal-text",
  "brand-rose",
  "brand-rose-text",
  "brand-violet",
  "brand-violet-text",
  "status-success",
  "status-warning",
  "status-danger",
  "status-info",
  "status-neutral",
  "accent",
  "link",
  "link-hover",
] as const;

const fonts = ["sans", "serif", "mono"] as const;
const textSizes = [
  "xs",
  "sm",
  "base",
  "md",
  "lg",
  "xl",
  "2xl",
  "3xl",
  "4xl",
] as const;
const leadings = ["tight", "prose"] as const;
const weights = ["normal", "medium", "semibold", "bold"] as const;
const spacings = ["0", "1", "2", "3", "4", "5", "6", "8", "10"] as const;
const radii = ["sm", "md", "lg"] as const;

function map(prefix: string, key: string, sophieKey: string): string {
  return `--${prefix}-${key}: var(--sophie-${sophieKey});`;
}

export function generateTailwind(): string {
  const lines: string[] = [];

  for (const c of colors) lines.push(map("color", c, c));
  lines.push("");

  for (const f of fonts) lines.push(map("font", f, `font-${f}`));
  lines.push("");

  for (const s of textSizes) lines.push(map("text", s, `text-${s}`));
  lines.push("");

  for (const l of leadings) lines.push(map("leading", l, `leading-${l}`));
  lines.push("");

  for (const w of weights) lines.push(map("font-weight", w, `weight-${w}`));
  lines.push("");

  for (const s of spacings) lines.push(map("spacing", s, `space-${s}`));
  lines.push("");

  for (const r of radii) lines.push(map("radius", r, `radius-${r}`));

  const indented = lines.map((l) => (l ? `  ${l}` : "")).join("\n");

  return `/* Generated by @sophie/theme. Do not edit by hand. */

@import "./theme.css";

@theme {
${indented}
}
`;
}
