import { type DeepDiveEntry, slugify } from "@sophie/core/schema";
import type { Root } from "mdast";
import { visit } from "unist-util-visit";
import {
  type MdxJsxFlowElement,
  readCalloutAttributes,
  renderChildrenToHtml,
} from "../jsx-utils.ts";

/**
 * Pure extractor. Walks an mdast tree, emits one `DeepDiveEntry` per
 * `<Callout variant="deep-dive">` flow element in source order.
 *
 * Per ADR 0058 §R-deep-dive: `<Callout variant="the-more-you-know">`
 * is intentionally NOT walked — enrichment content sits outside the
 * eight-role taxonomy by design. The boundary is a feature; future
 * Callout variants must declare which side of the boundary they sit
 * on when graduating to (or staying outside of) pedagogy tracking.
 *
 * Anchor precedence (D-derive):
 *   1. explicit `id` (slugified)
 *   2. `slug(title)` when title is present
 *   3. positional fallback `dd-${counter}` (counter is per-chapter
 *      sequential, incremented once per matched deep-dive callout)
 *
 * Unlike misconceptions (which use the shared `deriveAsideAnchor`
 * helper via the shared `kind: "misconception"` branch with `name`
 * consultation), deep-dive has a simpler precedence chain — no
 * misconception-graph `name` field. We inline `slugify` here rather
 * than widening `deriveAsideAnchor`'s `AsideAnchorKind` union, which
 * is currently scoped to actual Aside kinds. If a third Callout
 * variant gains pedagogy-tracking with the same shape, this helper
 * graduates to a shared `deriveCalloutAnchor` (YAGNI until that
 * second caller exists).
 *
 * Throws on intra-chapter anchor collisions (D1 invariant — mirrors
 * misconceptions' M1).
 * Warns (non-production) on empty body (D3 invariant — soft check).
 */
export function extractDeepDives(
  tree: Root,
  chapterSlug: string
): DeepDiveEntry[] {
  const out: DeepDiveEntry[] = [];
  const seenAnchors = new Set<string>();
  let counter = 0;

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const el = node as MdxJsxFlowElement;
    if (el.name !== "Callout") return;
    const { variant, title, id } = readCalloutAttributes(el);
    if (variant !== "deep-dive") return;

    counter += 1;

    const explicitId = id?.trim();
    const trimmedTitle = title?.trim();
    const anchor = explicitId
      ? slugify(explicitId)
      : trimmedTitle
        ? slugify(trimmedTitle)
        : `dd-${counter}`;

    if (seenAnchors.has(anchor)) {
      throw new Error(
        `Intra-chapter anchor collision in chapter "${chapterSlug}": deep-dive anchor "${anchor}" generated by more than one source. (D1 invariant.)`
      );
    }
    seenAnchors.add(anchor);

    const body = renderChildrenToHtml(el.children);
    if (body.trim().length === 0) {
      if (
        typeof process === "undefined" ||
        process.env?.NODE_ENV !== "production"
      ) {
        console.warn(
          `[pedagogy-index] deep-dive in chapter "${chapterSlug}" anchor "${anchor}" has empty body. (D3 warning.)`
        );
      }
    }

    out.push({
      chapter: chapterSlug,
      anchor,
      title: trimmedTitle ?? "",
      body,
    });
  });

  return out;
}
