import { type DefinitionEntry, slugify } from "@sophie/core/schema";
import type { Root } from "mdast";
import { visit } from "unist-util-visit";
import {
  type MdxJsxFlowElement,
  readAsideAttributes,
  renderChildrenToHtml,
} from "../jsx-utils.ts";

/**
 * Pure extractor. Walks an mdast tree, finds JSX elements named
 * "Aside" with `kind="definition"`, returns one DefinitionEntry
 * per match. Throws when:
 *
 *   - A definition aside is missing a non-empty `title` (the Aside
 *     Zod refinement already catches this at the schema layer; this
 *     is a defense-in-depth check inside the extractor).
 *   - Two definitions in the same chapter slug to the same anchor
 *     (audit invariant #2 — intra-chapter slug collision).
 */
export function extractDefinitions(
  tree: Root,
  chapterSlug: string
): DefinitionEntry[] {
  const out: DefinitionEntry[] = [];
  const seenSlugs = new Set<string>();

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const el = node as MdxJsxFlowElement;
    if (el.name !== "Aside") return;
    const attrs = readAsideAttributes(el);
    if (attrs.kind !== "definition") return;

    const title = attrs.title?.trim();
    if (!title) {
      throw new Error(
        `<Aside kind="definition"> in chapter "${chapterSlug}" is missing a non-empty title.`
      );
    }

    const slug = attrs.id ? slugify(attrs.id) : slugify(title);

    if (seenSlugs.has(slug)) {
      throw new Error(
        `Intra-chapter slug collision in chapter "${chapterSlug}": slug "${slug}" is generated by more than one <Aside kind="definition">. Resolution: add an explicit \`id\` prop to disambiguate.`
      );
    }
    seenSlugs.add(slug);

    out.push({
      term: title,
      slug,
      body: renderChildrenToHtml(el.children),
      chapter: chapterSlug,
      anchor: slug,
    });
  });

  return out;
}
