import { type FigureUsageEntry, slugify } from "@sophie/core/schema";
import type { Root } from "mdast";
import { visit } from "unist-util-visit";
import { type MdxJsxFlowElement, readFigureAttributes } from "../jsx-utils.ts";

/**
 * Pure extractor. Walks an mdast tree, finds JSX elements named
 * "Figure" with a `name` prop (registry-mode usages), returns one
 * FigureUsageEntry per match. Inline-mode `<Figure src="...">` (no
 * `name`) is skipped — those figures are one-off illustrations that
 * don't enter the registry. Per PR-C3 decisions row 3 (two-tier
 * model: registry + per-chapter usages) and row 6 (per-usage
 * sequential numbering, canonical flag from JSX prop).
 *
 * Each entry gets:
 *   - `number`: per-chapter sequential, starting at 1, source order
 *   - `anchor`: `fig-${slugify(name)}-${counter}` (counter-suffixed so
 *     repeated uses of the same registry name in one chapter get
 *     unique anchors; F5 invariant defense-in-depth, see below)
 *   - `canonical`: true when the author opts in via the boolean-
 *     presence `canonical` JSX prop; false by default
 *   - `captionOverride`: trimmed `caption` JSX prop value if present
 *
 * Throws on intra-chapter anchor collision (F5). The counter-suffixed
 * anchor shape makes collisions unreachable from the auto-anchor path
 * (each iteration increments the counter), but the guard exists for
 * defense-in-depth: a future schema extension allowing explicit
 * anchor overrides would route through the same code path.
 *
 * Cross-chapter F3 (multiple canonical for the same name) is the
 * accumulator's job; see `addFigureUsages`.
 */
export function extractFigures(
  tree: Root,
  chapterSlug: string,
  chapterNumber?: number
): FigureUsageEntry[] {
  const out: FigureUsageEntry[] = [];
  const seenAnchors = new Set<string>();
  let counter = 0;

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const el = node as MdxJsxFlowElement;
    if (el.name !== "Figure") return;
    const attrs = readFigureAttributes(el);
    const name = attrs.name?.trim();
    if (!name) return; // inline-mode `<Figure src="...">` doesn't index

    counter += 1;
    const anchor = `fig-${slugify(name)}-${counter}`;

    if (seenAnchors.has(anchor)) {
      throw new Error(
        `Intra-chapter anchor collision in chapter "${chapterSlug}": figure anchor "${anchor}" is generated by more than one <Figure name="${name}">. (F5 invariant.)`
      );
    }
    seenAnchors.add(anchor);

    out.push({
      name,
      chapter: chapterSlug,
      anchor,
      number: counter,
      chapterNumber,
      canonical: attrs.canonical === true,
      captionOverride: attrs.caption?.trim() || undefined,
    });
  });

  return out;
}
