import { type KeyInsightEntry, slugify } from "@sophie/core/schema";
import type { Root } from "mdast";
import { visit } from "unist-util-visit";
import {
  type MdxJsxFlowElement,
  readAsideAttributes,
  renderChildrenToHtml,
} from "../jsx-utils.ts";

/**
 * Pure extractor. Walks an mdast tree, finds JSX elements named
 * "Aside" with `kind="key-insight"`, returns one KeyInsightEntry per
 * match. Per PR-C3 decisions row 7, the `title` prop is OPTIONAL on
 * key-insight asides; the anchor is derived from `id` > slug(title) >
 * `ki-${counter}` (counter is per-chapter sequential). The short
 * `ki-` prefix is the canonical auto-anchor shape; see the anchor
 * prefix table in `@sophie/core/schema/pedagogy-index.ts`.
 *
 * Throws on intra-chapter anchor collisions (defense-in-depth K1).
 * Warns (non-production) on empty body (defense-in-depth K2).
 */
export function extractKeyInsights(
  tree: Root,
  chapterSlug: string
): KeyInsightEntry[] {
  const out: KeyInsightEntry[] = [];
  const seenAnchors = new Set<string>();
  let counter = 0;

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const el = node as MdxJsxFlowElement;
    if (el.name !== "Aside") return;
    const attrs = readAsideAttributes(el);
    if (attrs.kind !== "key-insight") return;

    counter += 1;
    const titleSlug = attrs.title?.trim() ? slugify(attrs.title.trim()) : null;
    const explicitId = attrs.id?.trim() ? slugify(attrs.id.trim()) : null;
    const anchor = explicitId ?? titleSlug ?? `ki-${counter}`;

    if (seenAnchors.has(anchor)) {
      throw new Error(
        `Intra-chapter anchor collision in chapter "${chapterSlug}": key-insight anchor "${anchor}" is generated by more than one <Aside kind="key-insight">. Resolution: add an explicit \`id\` prop to disambiguate.`
      );
    }
    seenAnchors.add(anchor);

    const body = renderChildrenToHtml(el.children);
    if (body.trim().length === 0) {
      if (
        typeof process === "undefined" ||
        process.env?.NODE_ENV !== "production"
      ) {
        console.warn(
          `[pedagogy-index] <Aside kind="key-insight"> in chapter "${chapterSlug}" anchor "${anchor}" has empty body.`
        );
      }
    }

    out.push({
      title: attrs.title?.trim() || undefined,
      body,
      chapter: chapterSlug,
      anchor,
    });
  });

  return out;
}
