import {
  deriveAsideAnchor,
  type KeyInsightEntry,
  slugify,
} from "@sophie/core/schema";
import type { Root } from "mdast";
import { visit } from "unist-util-visit";
import {
  type MdxJsxFlowElement,
  readAsideAttributes,
  renderChildrenToHtml,
} from "../jsx-utils.ts";

/**
 * Pure extractor. Walks an mdast tree, finds JSX elements named
 * "Aside" with `kind="key-insight"`, returns one KeyInsightEntry per
 * match. Per PR-C3 decisions row 7, the `title` prop is OPTIONAL on
 * key-insight asides; the anchor is derived from `id` > slug(title) >
 * `ki-${counter}` (counter is per-chapter sequential). The short
 * `ki-` prefix is the canonical auto-anchor shape; see the anchor
 * prefix table in `@sophie/core/schema/pedagogy-index.ts`.
 *
 * Throws on intra-chapter anchor collisions (defense-in-depth K1).
 * Warns (non-production) on empty body (defense-in-depth K2).
 */
export function extractKeyInsights(
  tree: Root,
  unitId: string,
  artifactId: string
): KeyInsightEntry[] {
  const out: KeyInsightEntry[] = [];
  const seenAnchors = new Set<string>();
  let counter = 0;

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const el = node as MdxJsxFlowElement;
    if (el.name !== "Aside") return;
    const attrs = readAsideAttributes(el);
    if (attrs.kind !== "key-insight") return;

    counter += 1;
    // Route through @sophie/core's `deriveAsideAnchor` — same helper
    // the renderer uses, so anchor strings can never disagree between
    // the rendered DOM and the index (2026-05-19 unified-anchor PR).
    // The positional `ki-${counter}` fallback stays here (extractor
    // knows the position; renderer doesn't and emits no id when no
    // other source is available).
    const fallbackAnchor = `${artifactId}-ki-${counter}`;
    const anchor =
      deriveAsideAnchor({
        kind: "key-insight",
        id: attrs.id,
        title: attrs.title,
        fallback: fallbackAnchor,
      }) ?? fallbackAnchor;

    if (seenAnchors.has(anchor)) {
      throw new Error(
        `Intra-chapter anchor collision in chapter "${unitId}": key-insight anchor "${anchor}" is generated by more than one <Aside kind="key-insight">. Resolution: add an explicit \`id\` prop to disambiguate.`
      );
    }
    seenAnchors.add(anchor);

    const body = renderChildrenToHtml(el.children);
    if (body.trim().length === 0) {
      if (
        typeof process === "undefined" ||
        process.env?.NODE_ENV !== "production"
      ) {
        console.warn(
          `[pedagogy-index] <Aside kind="key-insight"> in chapter "${unitId}" anchor "${anchor}" has empty body.`
        );
      }
    }

    const title = attrs.title?.trim() || undefined;
    out.push({
      title,
      body,
      unit: unitId,
      anchor,
      // W4c D4: derive a stable slug at extraction time. Use slugify(title)
      // when title present; fall back to `${unit}-${anchor}` (guaranteed
      // non-empty by Slug schema since both parts are themselves Slugs).
      // The KI-slug-unique audit invariant (Task 2.2) catches the cross-
      // unit collisions the fallback could otherwise allow.
      slug: title ? slugify(title) : `${unitId}-${anchor}`,
    });
  });

  return out;
}
