import {
  deriveAsideAnchor,
  type MisconceptionEntry,
} from "@sophie/core/schema";
import type { Root } from "mdast";
import { visit } from "unist-util-visit";
import {
  type MdxJsxFlowElement,
  type MisconceptionGraphFields,
  readAsideAttributes,
  readCalloutAttributes,
  renderChildrenToHtml,
} from "../jsx-utils.ts";

/**
 * Pure extractor. Walks an mdast tree, finds misconception entries
 * from BOTH source primitives in a single pass:
 *
 *   - `<Aside kind="misconception">` → `length: "short"` (compact,
 *     marginal-style misconception correction)
 *   - `<Callout variant="misconception">` → `length: "long"` (full-
 *     width block-style misconception correction)
 *
 * Per PR-C3 decisions row 8: a single extractor walks both source
 * components so the misconceptions index is fully aggregated under
 * one pedagogy role (ADR 0038's role-aggregation principle); the
 * length discriminator preserves the source-component visual
 * treatment downstream (decisions row 12).
 *
 * Anchor derivation matches `extractKeyInsights`: explicit `id` >
 * slug(title) > `misc-${counter}` (counter is per-chapter
 * sequential, incremented once per matched element across BOTH
 * source primitives in source order). The short `misc-` prefix is
 * the canonical auto-anchor shape; see the anchor prefix table in
 * `@sophie/core/schema/pedagogy-index.ts`.
 *
 * Throws on intra-chapter anchor collisions (M1 invariant).
 * Warns (non-production) on empty body (M3 invariant — soft check).
 */
export function extractMisconceptions(
  tree: Root,
  chapterSlug: string
): MisconceptionEntry[] {
  const out: MisconceptionEntry[] = [];
  const seenAnchors = new Set<string>();
  let counter = 0;

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const el = node as MdxJsxFlowElement;
    let length: "short" | "long";
    let attrs: {
      title?: string;
      id?: string;
      name?: string;
    } & MisconceptionGraphFields;

    if (el.name === "Aside") {
      const a = readAsideAttributes(el);
      if (a.kind !== "misconception") return;
      length = "short";
      attrs = {
        title: a.title,
        id: a.id,
        name: a.name,
        prerequisite_misconceptions: a.prerequisite_misconceptions,
        related_misconceptions: a.related_misconceptions,
        concept_refs: a.concept_refs,
        discipline_scope: a.discipline_scope,
      };
    } else if (el.name === "Callout") {
      const c = readCalloutAttributes(el);
      if (c.variant !== "misconception") return;
      length = "long";
      attrs = {
        title: c.title,
        id: c.id,
        // Callout doesn't surface a `name` attr today; if a future
        // Callout author adds one, the precedence chain below picks
        // it up automatically (anchor falls through to title-slug
        // when `name` is undefined).
        prerequisite_misconceptions: c.prerequisite_misconceptions,
        related_misconceptions: c.related_misconceptions,
        concept_refs: c.concept_refs,
        discipline_scope: c.discipline_scope,
      };
    } else {
      return;
    }

    counter += 1;
    // Route through @sophie/core's `deriveAsideAnchor` — same helper
    // the renderer uses, so anchor strings can never disagree between
    // the rendered DOM and the index (2026-05-19 unified-anchor PR).
    // The helper implements the misconception precedence
    // (id > name > slug(title)) per ADR 0044; the positional
    // `misc-${counter}` fallback stays here (extractor knows the
    // position; renderer doesn't and emits no id when no other source
    // is available). Closes the PR-γ → PR-δ coupling gap originally
    // surfaced during PR-δ scoping.
    const anchor =
      deriveAsideAnchor({
        kind: "misconception",
        id: attrs.id,
        name: attrs.name,
        title: attrs.title,
        fallback: `misc-${counter}`,
      }) ?? `misc-${counter}`;

    if (seenAnchors.has(anchor)) {
      throw new Error(
        `Intra-chapter anchor collision in chapter "${chapterSlug}": misconception anchor "${anchor}" generated by more than one source. (M1 invariant.)`
      );
    }
    seenAnchors.add(anchor);

    const body = renderChildrenToHtml(el.children);
    if (body.trim().length === 0) {
      if (
        typeof process === "undefined" ||
        process.env?.NODE_ENV !== "production"
      ) {
        console.warn(
          `[pedagogy-index] misconception in chapter "${chapterSlug}" anchor "${anchor}" has empty body. (M3 warning.)`
        );
      }
    }

    const entry: MisconceptionEntry = {
      body,
      chapter: chapterSlug,
      anchor,
      length,
      label: attrs.title?.trim() || undefined,
    };
    // Graph fields (ADR 0044). Omit when undefined to keep the
    // pre-ADR-0044 shape on misconceptions that don't declare any
    // relationships. Empty arrays are preserved (meaningful per the
    // schema reference doc).
    if (attrs.prerequisite_misconceptions !== undefined) {
      entry.prerequisite_misconceptions = attrs.prerequisite_misconceptions;
    }
    if (attrs.related_misconceptions !== undefined) {
      entry.related_misconceptions = attrs.related_misconceptions;
    }
    if (attrs.concept_refs !== undefined) {
      entry.concept_refs = attrs.concept_refs;
    }
    if (attrs.discipline_scope !== undefined) {
      entry.discipline_scope = attrs.discipline_scope;
    }
    out.push(entry);
  });

  return out;
}
