import {
  type OMIFlowEntry,
  type OMIFlowSlot,
  slugify,
} from "@sophie/core/schema";
import type { Root } from "mdast";
import { visit } from "unist-util-visit";
import {
  type MdxJsxFlowElement,
  readStringAttr,
  renderChildrenToHtml,
} from "../jsx-utils.ts";

type SlotKind = "observable" | "model" | "inference";

const SLOT_NAMES: Record<string, SlotKind> = {
  "OMIFlow.Observable": "observable",
  "OMIFlow.Model": "model",
  "OMIFlow.Inference": "inference",
};

/**
 * Pure extractor. Walks an mdast tree, emits one OMIFlowEntry per
 * `<OMIFlow>` flow element. Per ADR 0063:
 *
 *   - Strict-3-slot invariant: each <OMIFlow> MUST contain exactly
 *     one of each slot kind (observable / model / inference).
 *     Throws on missing or duplicated slots.
 *   - Slot-name binds role: <OMIFlow.Observable> → observable.
 *   - Source-order tolerance: any source order accepted; entry
 *     records the as-authored order in `sourceOrder` for OF-1.
 *   - Anchor precedence: id > slug(concept) > omi-${counter}.
 *   - Intra-chapter anchor collision throw.
 */
export function extractOMIFlows(
  tree: Root,
  chapterSlug: string
): OMIFlowEntry[] {
  const out: OMIFlowEntry[] = [];
  const seenAnchors = new Set<string>();
  let counter = 0;

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const el = node as MdxJsxFlowElement;
    if (el.name !== "OMIFlow") return;

    counter += 1;

    const explicitId = readStringAttr(el, "id");
    const concept = readStringAttr(el, "concept");
    const anchor = explicitId
      ? slugify(explicitId)
      : concept
        ? `omi-${slugify(concept)}`
        : `omi-${counter}`;

    if (seenAnchors.has(anchor)) {
      throw new Error(
        `Intra-chapter anchor collision in chapter "${chapterSlug}": OMIFlow anchor "${anchor}" generated by more than one source. (ADR 0063 anchor invariant.)`
      );
    }
    seenAnchors.add(anchor);

    const sourceOrder: SlotKind[] = [];
    const slots: Partial<Record<SlotKind, OMIFlowSlot>> = {};
    for (const child of el.children ?? []) {
      const childEl = child as MdxJsxFlowElement;
      if (childEl.type !== "mdxJsxFlowElement") continue;
      const kind = childEl.name ? SLOT_NAMES[childEl.name] : undefined;
      if (kind === undefined) continue;
      if (slots[kind] !== undefined) {
        throw new Error(
          `OMIFlow "${anchor}" in chapter "${chapterSlug}": slot "${kind}" appears more than once. (ADR 0063 exactly-one invariant.)`
        );
      }
      const title = readStringAttr(childEl, "title") ?? "";
      const body = renderChildrenToHtml(childEl.children);
      slots[kind] = { title, body };
      sourceOrder.push(kind);
    }

    for (const required of ["observable", "model", "inference"] as const) {
      if (slots[required] === undefined) {
        throw new Error(
          `OMIFlow "${anchor}" in chapter "${chapterSlug}": missing required slot "${required}". (ADR 0063 strict-3 invariant.)`
        );
      }
    }

    const observable = slots.observable;
    const model = slots.model;
    const inference = slots.inference;
    if (
      observable === undefined ||
      model === undefined ||
      inference === undefined
    ) {
      // Unreachable — the loop above throws before this point. The
      // explicit guard satisfies strict-null TypeScript without an `!`.
      throw new Error(
        `OMIFlow "${anchor}": slot detection invariant violated post-check.`
      );
    }

    out.push({
      chapter: chapterSlug,
      anchor,
      ...(concept ? { concept } : {}),
      observable,
      model,
      inference,
      sourceOrder: sourceOrder as [SlotKind, SlotKind, SlotKind],
    });
  });

  return out;
}
