import {
  type AuditFinding,
  slugify,
  type WorkedExampleEntry,
} from "@sophie/core/schema";
import type { Root } from "mdast";
import { visit } from "unist-util-visit";
import { type MdxJsxFlowElement, readStringAttr } from "../jsx-utils.ts";

/**
 * `<WorkedExample>` extractor (ADR 0081 + WS B+D, closes
 * [issue #188](https://github.com/drannarosen/sophie/issues/188)).
 *
 * Walks the mdast tree for `<WorkedExample>` JSX flow elements and
 * counts each callsite's slot children:
 *
 *   - `<WorkedExample.Problem>` → exactly one required (WE-2 ERROR)
 *   - `<WorkedExample.Step label?>` → zero or more
 *   - `<WorkedExample.DimCheck>` → zero or more (WE-1 WARNING when
 *      `steps ≥ 1` AND `dimChecks === 0`, the QB6 units-at-every-
 *      step coverage gap)
 *   - `<WorkedExample.Result>` → exactly one required (WE-2 ERROR)
 *
 * Children with any other JSX name are NOT silently skipped (R7
 * disposition, mirrors OMIFlow's OF-3): collected and emitted as
 * **WE-3 WARNING** entries so authors who add a non-slot child
 * (e.g., a misplaced `<Callout>` or stray prose-wrapped tag)
 * get a one-line build hint instead of a silent absence in the
 * audit graph. Whitespace text nodes and prose paragraphs are
 * tolerated (worked examples have inline math + prose between
 * steps); only JSX flow elements with the wrong tagName fire WE-3.
 *
 * Anchor precedence (mirrors OMIFlow's design):
 *   1. explicit `id=` attr (slugified) wins
 *   2. else `we-${slug(title)}` when `title=` is present
 *   3. else positional fallback `we-${counter}` (chapter-scoped)
 *
 * Throws on intra-chapter anchor collision. The audit invariants
 * (WE-1, WE-2, WE-3) live in
 * `packages/astro/src/lib/pedagogy-audit/invariants/worked-examples.ts`.
 *
 * `<WorkedExample.DimCheck>` carries the `data-dim-check` runtime
 * attribute (QB6 hook); the extractor doesn't look at runtime
 * attrs — slot presence is the WE-1 signal at audit-time.
 */

const SLOT_NAMES: Record<string, "problem" | "step" | "dim-check" | "result"> =
  {
    "WorkedExample.Problem": "problem",
    "WorkedExample.Step": "step",
    "WorkedExample.DimCheck": "dim-check",
    "WorkedExample.Result": "result",
  };

export interface WorkedExampleExtractionResult {
  entries: WorkedExampleEntry[];
  findings: AuditFinding[];
}

function deriveAnchor(
  el: MdxJsxFlowElement,
  counter: number
): { anchor: string; title: string | undefined } {
  const explicitId = readStringAttr(el, "id");
  const title = readStringAttr(el, "title");
  if (explicitId) return { anchor: slugify(explicitId), title };
  if (title) return { anchor: `we-${slugify(title)}`, title };
  return { anchor: `we-${counter}`, title };
}

export function extractWorkedExamples(
  tree: Root,
  unitId: string
): WorkedExampleExtractionResult {
  const entries: WorkedExampleEntry[] = [];
  const findings: AuditFinding[] = [];
  const seenAnchors = new Set<string>();
  let counter = 0;

  visit(tree, "mdxJsxFlowElement", (node: unknown) => {
    const el = node as MdxJsxFlowElement;
    if (el.name !== "WorkedExample") return;

    counter += 1;
    const { anchor, title } = deriveAnchor(el, counter);

    if (seenAnchors.has(anchor)) {
      throw new Error(
        `Intra-chapter anchor collision in chapter "${unitId}": WorkedExample anchor "${anchor}" generated by more than one source. Resolution: set explicit \`id\` props to disambiguate, or rename titles.`
      );
    }
    seenAnchors.add(anchor);

    let problemCount = 0;
    let stepCount = 0;
    let dimCheckCount = 0;
    let resultCount = 0;
    const unknownChildNames: string[] = [];

    for (const child of el.children ?? []) {
      const childEl = child as MdxJsxFlowElement;
      // Only JSX flow elements are slot candidates. Prose paragraphs,
      // inline math, and other mdast nodes between slots are tolerated.
      if (childEl.type !== "mdxJsxFlowElement") continue;
      const slotKind = childEl.name ? SLOT_NAMES[childEl.name] : undefined;
      if (slotKind === undefined) {
        unknownChildNames.push(childEl.name ?? "?");
        continue;
      }
      if (slotKind === "problem") problemCount += 1;
      else if (slotKind === "step") stepCount += 1;
      else if (slotKind === "dim-check") dimCheckCount += 1;
      else if (slotKind === "result") resultCount += 1;
    }

    entries.push({
      unit: unitId,
      anchor,
      ...(title ? { title } : {}),
      number: counter,
      slots: {
        problem: problemCount === 1,
        steps: stepCount,
        dimChecks: dimCheckCount,
        result: resultCount === 1,
      },
    });

    // R7 disposition — unknown JSX flow children produce WE-3 WARNINGs
    // (one per offending child). The example still extracts cleanly;
    // WE-3 surfaces the rogue child to the author without blocking the
    // build.
    for (const childName of unknownChildNames) {
      findings.push({
        severity: "WARNING",
        code: "WE-3",
        message: `WE-3: WorkedExample "${anchor}" in chapter "${unitId}" contains unknown JSX child <${childName}>. Valid <WorkedExample> children per ADR 0081 are <WorkedExample.Problem>, <WorkedExample.Step>, <WorkedExample.DimCheck>, <WorkedExample.Result>. Resolution: remove the rogue element, or move it outside the <WorkedExample>...</WorkedExample> wrapper.`,
        location: { unit: unitId, anchor },
      });
    }

    // WE-2 over-count surfaced ASAP at extract time — duplicate
    // .Problem or .Result is a structural error that authors should
    // see at the offending callsite rather than in the audit summary.
    if (problemCount > 1) {
      throw new Error(
        `WorkedExample "${anchor}" in chapter "${unitId}": <WorkedExample.Problem> slot appears ${problemCount} times. Exactly one required (WE-2).`
      );
    }
    if (resultCount > 1) {
      throw new Error(
        `WorkedExample "${anchor}" in chapter "${unitId}": <WorkedExample.Result> slot appears ${resultCount} times. Exactly one required (WE-2).`
      );
    }
  });

  return { entries, findings };
}
